define.module "bishop"

require "bishop.console"
require "bishop.drawable"
require "bishop.screen"
require "bishop.effect"
require "bishop.entity"
require "bishop.asset"
require "bishop.state"
require "bishop.controller"
require "bishop.map"
require "bishop.game"
